### ISSUE TITLE
Question on Shopping Cart example

### ISSUE THREAD

**Issue by zeeshanjan82** [btroncone/ngrx-examples#14] opened 2016-06-19 06:01 UTC
@btroncone In the shopping-cart ngrx-example I am little confused on the switch case for RECEIVED_BOOKS
````js
export default function (state = initialState, action: Action): BooksState {
    switch (action.type) {
        case RECEIVED_BOOKS:
            return {
                entities: Object.assign({},
                    state.entities,
                    action.payload.reduce((obj, book) => {
                        obj[book.id] = book;
                        return obj;
                    }, {})
                )
            };
        default:
            return state;
    }
};
````
In this case inside the case RECEIVED_BOOKS as I understand we are creating new entities array by using Object.assign with the existing state.entities but I did not understand the 3rd param to Object.assign function.
in this reducer we are receiving the books so we could have done like this also
entities: 
````js
Object.assign({}, state.entities, action.payload)
````

**Comment by btroncone** [comment] 2016-07-09 18:52
Sorry for the delayed response, this looks like a typo. I will fix soon! 👍

**Comment by btroncone** [comment] 2016-07-10 12:39
I misread this I first responded. The  object there is the seed value or reduce, not a 3rd value for Object.assign. This is written as intended. I am closing this issue. :smile:

**Closed by btroncone** 2016-07-10 12:39 UTC
